### ISSUE TITLE
Decision post about "atomic commits/PRs" and Conventional commits/branches

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/decisions#17]
We are already doing this but should have a decision post about it.

**Comment by henrik-goul** [comment]
@lwjohnst86 I assume that this task was assigned to me by mistake ;)

**Comment by lwjohnst86** [comment]
Ha yes you are right haha

**Comment by signekb** [comment]
This is a duplicate of seedcase-project/team#39, seedcase-project/team#90, seedcase-project/team#91.
