### ISSUE TITLE
Discussion: Do we want a logo for each part of Seedcase or one for all of them?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/decisions#30]
@henrik-goul @philter87 @K-Beicher @lwjohnst86 @signekb 
As discussed at the update meeting 17 February, I hereby create an issue for the discussion of whether we would like one overall Seedcase logo or we would want individual logos for each part of Seedcase - i.e., `sprout`, `propagate`, `flower`, and `garden`

For example, [tidyverse](https://www.tidyverse.org/) has individual logos for each package in their "universe":
![Image](https://github.com/seedcase-project/decisions/assets/40836345/d8a64073-542f-4cf0-b4ae-50db010ef91c)

Pros for only one logo: 
- It's simple
- It clearly collects all parts of Seedcase into a union of "the Seedcase Software Product" - they are individual parts of the same software
Cons: 
- Might be more difficult to differentiate the separate parts of Seedcase 

Pros for multiple logos: 
- The different parts will be more easy to differentiate if they are separated visually as well
Cons: 
- Too many logos? 

Please feel free to add/edit the list above - and/or add comments!

**Comment by signekb** [comment]
Will close this for now.
