### ISSUE TITLE
docs: Update 'Why Quarto' with options and expand on decision

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/decisions#40]
https://github.com/seedcase-project/decisions/blob/9177ba86d509bac1354ab0981efc9cc01b9731f7/why-quarto.qmd#L10

**Comment by signekb** [comment]
(assigning you @K-Beicher, since you're assigned to the PR #48 - but maybe it should actually be @lwjohnst86 since you filled out the options?)

**Comment by K-Beicher** [comment]
I was thinking that I would set up individual issue for the completion of the why files, so that someone else could complete them if you felt like it.

**Comment by K-Beicher** [comment]
This has been done while reviewing the first changes
