### ISSUE TITLE
[discussion]: Is the Why Docker file still relevant?

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/decisions#57]
### What would you like to discuss?

With the development work done on Sprout it seem like we are moving away from the initially suggested solution with two Docker containers, one holding the backend data, and the other hosting the frontend.

As we have been updating the decision documents it would be helpful to decide if we should archive document on Docker containers, or if we should rework it to fit the new template.

**Comment by lwjohnst86** [comment]
We still use Docker, and we will probably use it for installing to servers, but you're right, it needs an update.

**Comment by K-Beicher** [comment]
I'll get that sorted as well.
