### ISSUE TITLE
[discussion]: Do we want to archive the Why Containers post for now?

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/decisions#58]
### What would you like to discuss?

At the moment it is unclear if we can get the containers/devcontainer to work with the way Seedcase is set up. In light of this, should we put the decision post on Containers on hold, or go ahead and convert it to the new template. The post is currently quite a way from fitting the template, and it is missing a couple of large sections.

**Comment by lwjohnst86** [comment]
We do use containers (for deploying the demo, and using Docker is a container). I don't think there is any mention of devcontainers inside it though. We haven't yet really used devcontainers, even though I really like them in theory. But yea, this post needs an update.

**Comment by K-Beicher** [comment]
I'll create an issue for that once I've moved things across as best I can.
