### ISSUE TITLE
[discussion]: Are we happy with the decision post on Fly?

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/decisions#59]
### What would you like to discuss?

The decision post on Fly is written quite recently, but does not follow the template for out Why documentation. It is a very comprehensive post, but it would require quite a bit of work to transfer it.

> Can we live with a decision post which doesn't conform to the template?

**Comment by K-Beicher** [comment]
@lwjohnst86 here is one for you (I think) to have a think about. I'd be happy to keep this one as is, and maybe one day re-work it.

**Comment by lwjohnst86** [comment]
I think it's fine the way it is, even though it doesn't follow the template. Closing.
