### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/decisions#64]
Just some potential layout improvements, as per  https://github.com/seedcase-project/team/issues/142. 

* Posts displayed as cards: I think this looks good, however, the more posts we have, the harder it will become to get an overview of what’s available because you have to click through all the pages. Would it make sense to group them into topics? Maybe something like: project management, technical workflow (e.g. git-related things, code snippets), tech stack (e.g. front end, API, database). 
* These topics could live in a sidebar like on the team website, for example. This would also allow you to go from post to post without having to go back to the landing page.
~~* I know we already have categories, but I don’t think(?) it’s possible to look at all posts tagged with a given category.~~ moved to #83 
~~* Remove the template decision post from the landing page.~~ duplicate of #67

**Comment by lwjohnst86** [comment]
Basically done, or will be done in other issues.
